"""Initial migration

Revision ID: 0c0c9041e631
Revises: 
Create Date: 2026-09-18 00:47:45.751994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0c9041e631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_username', sa.String(length=100), nullable=False),
    sa.Column('player2_username', sa.String(length=100), nullable=True),
    sa.Column('state_pieces', sa.JSON(), nullable=False),
    sa.Column('current_player', sa.String(length=20), nullable=True),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('rss_url', sa.String(length=300), nullable=False),
    sa.Column('rss_author', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_template',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_template')
    op.drop_table('rss_feeds')
    op.drop_table('game')
    # ### end Alembic commands ###
