"""add podcast name field

Revision ID: 181cde8ec3b8
Revises: d716af1dba4a
Create Date: 2026-04-08 19:32:13.584757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181cde8ec3b8'
down_revision = 'd716af1dba4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_author', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.drop_column('rss_author')

    # ### end Alembic commands ###
