"""add high_score column

Revision ID: 289f5871f0e1
Revises: c86dfef49de6
Create Date: 2026-03-31 12:25:13.832609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289f5871f0e1'
down_revision = 'c86dfef49de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.drop_column('high_score')

    # ### end Alembic commands ###
