"""added new table, removed rss_url from user_templatess

Revision ID: 2d18a9c827e2
Revises: 665a414cb434
Create Date: 2026-03-31 20:15:33.303709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d18a9c827e2'
down_revision = '665a414cb434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feeds',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.drop_column('rss_feed_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_feed_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    op.drop_table('rss_feeds')
    # ### end Alembic commands ###
