"""initial migration

Revision ID: 611314aaae3b
Revises: 
Create Date: 2026-03-22 13:19:15.792289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611314aaae3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('password')
    )
    op.drop_table('users_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_template',
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pass', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('username', name=op.f('users_template_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
