"""add rss_feed_url column

Revision ID: 665a414cb434
Revises: 289f5871f0e1
Create Date: 2026-03-31 15:18:02.700027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665a414cb434'
down_revision = '289f5871f0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_feed_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.drop_column('rss_feed_url')

    # ### end Alembic commands ###
