"""initial migration

Revision ID: 6ec5e5ab5293
Revises: 611314aaae3b
Create Date: 2026-03-22 13:26:50.104286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec5e5ab5293'
down_revision = '611314aaae3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_template',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('password')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name=op.f('user_pkey')),
    sa.UniqueConstraint('password', name=op.f('user_password_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users_template')
    # ### end Alembic commands ###
