"""add id field to rss_feed

Revision ID: 82778af84483
Revises: 2d18a9c827e2
Create Date: 2026-04-08 14:38:17.416086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82778af84483'
down_revision = '2d18a9c827e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rss_url', sa.String(length=300), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_column('rss_url')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
