"""modification to password field

Revision ID: c86dfef49de6
Revises: 6ec5e5ab5293
Create Date: 2026-03-22 15:46:47.980168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86dfef49de6'
down_revision = '6ec5e5ab5293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_template_password_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_template', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_template_password_key'), ['password'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
