"""empty message

Revision ID: d137da587c5c
Revises: 0c0c9041e631
Create Date: 2026-09-18 12:54:12.435077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd137da587c5c'
down_revision = '0c0c9041e631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.drop_column('rss_author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_author', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
