"""add rss_title to rss_feeds

Revision ID: e5f6a1b2c3d4
Revises: d137da587c5c
Create Date: 2026-09-18 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6a1b2c3d4'
down_revision = 'd137da587c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.drop_column('rss_title')

    # ### end Alembic commands ###